### PR TITLE
permission refinements

### PR DESCRIPTION
**Pull request by Loui4**

### CODE REVIEW

**Review by bwighane — CHANGES_REQUESTED** [review]
Onboard me, why do we need to specify every field in the facility model for a write operation. I'm guessing if one has the ability to create a facility then they can fill all of those. Besides, if we want to lock one field in the model we can focus on that one alone in the ACLs. I may be getting it wrong.

**Comment by Loui4** [comment]
according to my understanding,  updating fields represents different operations that are segregated amongst the roles. For instance, the DHO cannot register facility as such the ACLs will prohibit the  DHO from making changes on the registration_number field. However, the DHO can alter some other details of the facility. When creating the facility the registration_number is null.

**Comment by Loui4** [comment]
I think @caspater can shed more light.

**Comment by caspater** [comment]
[MASTER HEALTH FACILITY REGISTRY USER ROLES.docx](https://github.com/Kuunika/MHFR/files/5847747/MASTER.HEALTH.FACILITY.REGISTRY.USER.ROLES.docx)

When adding , we can permit all fields but when updating we are supposed to guard the other fields like what @Loui4 said. From the document, take medical_council user, they can only update three fields which means the other fields will have to be protected.

So, for anyone who can create a facility, allow all fields; and for updating put the field checks

**Comment by bwighane** [comment]
Okay, that makes sense.

**Review by bwighane — APPROVED** [review]

**Pull request merged**
